[workspace]
members = [
  "focus/commands",
  "focus/internals",
  "focus/operations",
  "focus/repo-management",
  "focus/testing",
  "focus/tracing",
  "focus/util",
  "tool_insights_client",
  "content-addressed-cache",
]
