[package]
name = "focus-commands"
version = "0.1.0"
authors = ["Wilhelm Bierbaum <wilhelm@twitter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.11", features = ["executor", "thread-pool"] }
protobuf = "2.20.0"
focus-internals = { path = "../internals" }
focus-formats = { path = "../formats" }
anyhow = "1.0.38"
log = "0.4.13"
thiserror = "1.0.23"
dirs = "3.0.1"
git2 = { version = "0.13.15", default-features = false }
serde = "1.0.119"
serde_derive = "1.0.119"
signal-hook = "0.3.3"
structopt = "0.3.21"
tempfile = "3.2.0"
toml = "0.5.8"
uuid = { version = "0.8.2", features = ["v4"] }
crossbeam-utils = "0.8.1"
futures-channel = "0.3.11"
serde_json = "1.0.61"
env_logger = "0.8.2"
rocksdb = "0.16.0"
pretty-hex = "0.2.1"    # Pretty hex dump of bytes slice in the common style.
lazy_static = "1.4.0"
sha2 = "0.9.5"
prost = "0.7"
tonic = "0.4"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "process", "fs"] }
tokio-stream = "0.1"
async-stream = "0.3"
walkdir = "2.3.2"
nix = "0.21.0"

[[bin]]
name = "focus-repo-manager"
path = "src/server/main.rs"

[[bin]]
name = "focus-treesnap"
path = "src/treesnap/main.rs"

[[bin]]
name = "focus-parachute"
path = "src/parachute/main.rs"
