[package]
name = "focus-commands"
version = "0.1.0"
authors = ["Wilhelm Bierbaum <wilhelm@twitter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.16", features = ["executor", "thread-pool"] }
protobuf = "2.24.1"
focus-internals = { path = "../internals" }
focus-formats = { path = "../formats" }
anyhow = "1.0.42"
log = "0.4.14"
thiserror = "1.0.26"
dirs = "3.0.2"
git2 = { version = "0.13.20", default-features = false }
serde = "1.0.127"
signal-hook = "0.3.9"
structopt = "0.3.22"
tempfile = "3.2.0"
uuid = { version = "0.8.2", features = ["v4"] }
crossbeam-utils = "0.8.5"
futures-channel = "0.3.16"
serde_json = "1.0.66"   
env_logger = "0.9.0"
pretty-hex = "0.2.1"
lazy_static = "1.4.0"
sha2 = "0.9.5"
prost = "0.8.0"
walkdir = "2.3.2"
serde_derive = "1.0.127"

##
## Focus CLI: The primary UI for Project Focused Development
##
[[bin]]
name = "focus"
path = "src/cli/main.rs"

##
## Treesnap: Tools to produce source tree images
##
[[bin]]
name = "treesnap"
path = "src/treesnap/main.rs"

