---
twgit:
  version: 1
  repos:
    - name: derp
      defaults:
        host: "derp.biz"
        readonlyhost: "herpderp.biz"
        scheme: https
      profiles:
        - role: main
          backend: "{{.Scheme}}://{{.Host}}/{{.Repo}}/{{.Role}}"  # <<-- s/https/{{.Scheme}}/
  hasher:
    # this seems to be a big enough prime. altering this value
    # did not seem to have a significant effect on the distribution
    partitioncount: 9973

    # this replication factor was chosen after hashing
    # all users in source against 14 backends with 9973 as the
    # partition count.
    #
    # min: 209, max: 253, mean: 224.642857, variance: 184.372449, stdev: 13.578382
    #
    replicationfactor: 34

    # I'm not really sure what this does, it's the default in the examples given
    # for the hashing library we're using so i'm assuming it's a sane value
    load: 1.25

