---
version: "3.6"
services:
  apache:
    build:
      context: ./apache2
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - type: bind
        source: /repos/source
        target: /srv/git
      - type: bind
        source: ./apache2/apache.conf
        target: /usr/local/apache2/conf/httpd.conf
        read_only: true
      - type: bind
        source: ./apache2/git.conf
        target: /usr/local/apache2/conf/extra/git.conf
        read_only: true
      - type: bind
        source: ./apache2/html
        target: /var/www/html
      - type: bind
        source: ./apache2/cgi-bin
        target: /opt/twgit/cgi-bin
