[package]
name = "focus-internals"
version = "0.1.0"
authors = ["Wilhelm Bierbaum <wilhelm@twitter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
log = "0.4.13"
env_logger = "0.8.2"
thiserror = "1.0.23"
dirs = "3.0.1"
git2 = { version = "0.13.15", default-features = false }
serde = "1.0.119"
serde_derive = "1.0.119"
signal-hook = "0.3.3"
structopt = "0.3.21"
tempfile = "3.2.0"
toml = "0.5.8"
protobuf = "2.20.0"
crossbeam-utils = "0.8.1"
rocksdb = "0.16.0"
uuid = { version = "0.8.2", features = ["v4"] }
bufstream = "0.1.4"
crossbeam-queue = "0.3.1"
tonic = "0.4"
prost = "0.7"
# tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
http = "0.2"

# [build-dependencies]
# tonic-build = "0.4"

[lib]
name = "internals"
path = "src/lib.rs"
