[package]
name = "focus-internals"
version = "0.1.0"
authors = ["Wilhelm Bierbaum <wilhelm@twitter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
bufstream = "0.1.4"
crossbeam-queue = "0.3.2"
crossbeam-utils = "0.8.5"
dirs = "3.0.2"
env_logger = "0.9.0"
focus-formats = { path = "../formats" }
git2 = { version = "0.13.20", default-features = false }
http = "0.2.4"
log = "0.4.14"
nix = "0.22.0"
prost = "0.8.0"
serde = "1.0.126"
serde_derive = "1.0.126"
signal-hook = "0.3.9"
structopt = "0.3.22"
tempfile = "3.2.0"
thiserror = "1.0.26"
toml = "0.5.8"
uuid = { version = "0.8.2", features = ["v4"] }

[lib]
name = "internals"
path = "src/lib.rs"
