[package]
name = "focus-internals"
version = "0.1.0"
authors = ["Wilhelm Bierbaum <wilhelm@twitter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
bufstream = "0.1.4"
crossbeam-queue = "0.3.1"
crossbeam-utils = "0.8.1"
dirs = "3.0.1"
env_logger = "0.8.2"
focus-formats = { path = "../formats" }
git2 = { version = "0.13.15", default-features = false }
http = "0.2"
log = "0.4.13"
nix = "0.21.0"
prost = "0.7"
protobuf = "2.20.0"
rocksdb = "0.16.0"
serde = "1.0.119"
serde_derive = "1.0.119"
signal-hook = "0.3.3"
structopt = "0.3.21"
tempfile = "3.2.0"
thiserror = "1.0.23"
toml = "0.5.8"
tonic = "0.4"
uuid = { version = "0.8.2", features = ["v4"] }

# [build-dependencies]
# tonic-build = "0.4"

[lib]
name = "internals"
path = "src/lib.rs"
