# Copyright 2022 Twitter, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Twitter-internal build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.60.0
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c

      - name: Compile (but don't test) `twttr` feature
        run: cargo build --features ci,twttr --all-targets --workspace
